include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - tools/**
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Treat these as warnings instead of errors
    deprecated_member_use: warning
    deprecated_member_use_from_same_package: warning

linter:
  rules:
    # Disable some rules that conflict with our code style
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    prefer_single_quotes: true